CMAKE_BUILD_TYPE ?= RelWithDebInfo
CMAKE_EXTRA_FLAGS ?= -DCMAKE_INSTALL_PREFIX:PATH=/opt/neovim-nightly
DEPS_CMAKE_FLAGS ?= -DUSE_BUNDLED=ON -DUSE_EXISTING_SRC_DIR=ON -DUSE_BUNDLED_LUAROCKS=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_GPERF=OFF
# Force Lua on architectures where Luajit doesn't work
ifneq (,$(filter arm64,$(shell dpkg-architecture -qDEB_HOST_ARCH 2>/dev/null)))
  CMAKE_EXTRA_FLAGS += -DPREFER_LUA=ON
  DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_LUA=OFF
else
  CMAKE_EXTRA_FLAGS += -DPREFER_LUA=OFF
endif
