CMAKE_BUILD_TYPE ?= RelWithDebInfo
CMAKE_EXTRA_FLAGS ?= -DCMAKE_INSTALL_PREFIX:PATH=/usr -DPREFER_LUA=OFF
DEPS_CMAKE_FLAGS ?= -DUSE_EXISTING_SRC_DIR=ON -DUSE_BUNDLED_LUAROCKS=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_GPERF=OFF
