name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Debian repository
        uses: actions/checkout@v2
        with:
          path: neovim-debian
      - name: Checkout Neovim repository
        uses: actions/checkout@v2
        with:
          repository: neovim/neovim
          path: neovim
      - name: Checkout Neovim repository
        uses: actions/checkout@v2
        with:
          repository: neovim/deps
          path: deps
      - name: Merge repositories
        run: |
          cd neovim
          cp -R ../neovim-debian/* .
          mv ../deps/src deps-src
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends devscripts equivs
          cd neovim
          sudo mk-build-deps --install --remove --tool "apt-get --no-install-recommends --yes" ./debian/control
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Build Package
        run: |
          cd neovim
          dch --newversion="$(head -n 1 debian/changelog | awk '{print $2}' | sed -e 's:[()]::g')+git$(date +%Y%m%d%H%M)" "Auto release"
          dpkg-buildpackage -uc -us -b
